FROM docker.io/library/postgres:15

# Create a directory for SSL certificates
RUN mkdir -p /var/lib/postgresql/certs

COPY keys_and_certs/postgres_ssl_server.crt /var/lib/postgresql/certs/server.crt
COPY keys_and_certs/postgres_server.key /var/lib/postgresql/certs/server.key

# Set the appropriate permissions for the SSL key
RUN chmod 600 /var/lib/postgresql/certs/server.key
RUN chown postgres:postgres /var/lib/postgresql/certs/server.key /var/lib/postgresql/certs/server.crt

# Append SSL configuration to the default postgresql.conf
RUN echo "ssl = on" >> /usr/share/postgresql/postgresql.conf.sample && \
    echo "ssl_cert_file = '/var/lib/postgresql/certs/server.crt'" >> /usr/share/postgresql/postgresql.conf.sample && \
    echo "ssl_key_file = '/var/lib/postgresql/certs/server.key'" >> /usr/share/postgresql/postgresql.conf.sample && \
    echo "listen_addresses = '*'" >> /usr/share/postgresql/postgresql.conf.sample
